# Generated by Django 4.2.7 on 2024-03-02 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 2, 2, 24, 54, 999421, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
